spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl: create

path:
  apiPrefix: /api

kafka:
  bootstrap_server: localhost:9093
  group_id: my-group-id
  topics:
    producer:
      post: post-student
