name: Build and Analyze

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          # Remove any existing maven installation if necessary
          sudo rm -f /usr/bin/mvn
          # Download and install Maven
          curl -sL https://www.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz | sudo tar xz -C /opt
          # Create a symbolic link
          sudo ln -s /opt/apache-maven-3.8.8/bin/mvn /usr/bin/mvn

      - name: Configure Maven settings
        run: |
          echo '<settings><profiles><profile><id>sonar</id><properties><sonar.host.url>https://sonarcloud.io</sonar.host.url><sonar.login>${{ secrets.SONAR_TOKEN }}</sonar.login></properties></profile></profiles><activeProfiles><activeProfile>sonar</activeProfile></activeProfiles></settings>' > ~/.m2/settings.xml

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify Maven Version
        run: mvn --version

      - name: Build and analyze with SonarCloud
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=vlad-vinskevitch_backendforfrontedservice-sox \
          -Dsonar.organization=sitionix \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
          -Dsonar.pullrequest.branch=${{ github.head_ref }} \
          -Dsonar.pullrequest.base=${{ github.base_ref }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -X
